name: Bandit Security Scan

on:
    push:
    pull_request:

jobs:
    bandit-security:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run Bandit Scan
              uses: py-actions/bandit@v1
              with:
                  path: "."
                  options: "-r . --severity-level high"
